server:
  port: 8802

spring:
  application:
    name: cloud-rabbitmq-consumer
  rabbitmq:
    addresses: localhost
    port: 15672
    username: guest
    password: guest



eureka:
  client:
    register-with-eureka: true #表示将自己向注册中心注册 默认true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合使用ribbon使用负载均衡
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/ #单机版
  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群
  instance:
    instance-id: rabbitmq-consumer8802
    prefer-ip-address: true
