server:
  port: 80

eureka:
  client:
    register-with-eureka: false #表示不将自己向注册中心注册 默认true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


feign:
  hystrix:
    enabled: true