server:
  port: 9527

eureka:
  instance:
    name: cloud-gateway-service
  client:
    register-with-eureka: true #表示将自己向注册中心注册 默认true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合使用ribbon使用负载均衡
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://localhost:7001/eureka/ #单机版
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #配置路由ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #配置路由ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery/** #断言，路径相匹配的进行路由



