server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        enabled: true
        enable-auto-data-source-proxy: true #是否开启数据源自动代理,默认为true
        #自定义事务组的名称需要和seata-server中的对应
        tx-service-group: fsp_tx_group
        registry:  #registry根据seata服务端的registry配置
          type: nacos #默认为file
          nacos:
            application: seata-server #配置自己的seata服务
            server-addr: 127.0.0.1:8848 #根据自己的seata服务配置
            username: "nacos" #根据自己的seata服务配置
            password: "nacos" #根据自己的seata服务配置
            namespace: ""  #根据自己的seata服务配置
            cluster: default # 配置自己的seata服务cluster, 默认为 default
            group: SEATA_GROUP #根据自己的seata服务配置
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848

  datasource:
    name: druidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-2zefzzv3s8d74dyfvho.pg.rds.aliyuncs.com:3432/seata_order
    type: com.alibaba.druid.pool.DruidDataSource
    username: aranya_staging #\u7528\u6237\u540D
    password: e23TsmZasGyEAqd2018 #\u5BC6\u7801
    seata: false    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  #  mapper-locations: classpath*:mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguitu.springcloud.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u67E5\u8BE2sql\u65E5\u5FD7\u663E\u793A\u5728\u63A7\u5236\u53F0,\u8FD9\u4E2A\u662F\u53EF\u4EE5sql\u3001\u53C2\u6570\u3001\u67E5\u8BE2\u7ED3\u679C\u7684

management:
  endpoints:
    web:
      exposure:
        include=*: